Gitar.Web/Models/ErrorViewModel.cs
namespace Gitar.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Gitar.Web/ViewModels/GitRepositoriesViewModel.cs
using Gitar.Domain.Models;

namespace Gitar.Web.ViewModels;

public class GitRepositoriesViewModel
{
    public string? Username { get; set; }
    public List<GitRepository>? GitRepositories { get; set; }
}

Gitar.Web/Controllers/GitarController.cs
using Gitar.Application.DTO;
using Gitar.Domain.Contracts.Data;
using Gitar.Domain.Contracts.Infrastructure;
using Gitar.Domain.Models;
using Gitar.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Gitar.Web.Controllers;

public class GitarController : Controller
{
    private readonly IRepository<GitUser, Guid> _gitUserRepository;
    private readonly IGitService _gitService;

    public GitarController(IRepository<GitUser, Guid> gitUserRepository, IGitService gitService)
    {
        _gitUserRepository = gitUserRepository;
        _gitService = gitService;
    }

    public async Task<IActionResult> Index()
    {
        var users = await _gitUserRepository.GetAsync();

        if (!users.Any())
        {
            var neurouz = new GitUser()
            {
                Name = "neurouz",
                ImageUrl = "https://avatars.githubusercontent.com/u/40274500?v=4",
                IsActive = true,
                Blog = "http://neurouz.ddns.net",
                Followers = 18,
                Following = 33,
                GithubId = 40274500,
                ProfileUrl = "https://github.com/neurouz",
                PublicRepoCount = 9
            };

            await _gitUserRepository.CreateAsync(neurouz);
            users.Add(neurouz);
        }

        return View(users);
    }

    public async Task<IActionResult> GetUsersPartial()
    {
        var users = await _gitUserRepository.GetAsync();

        return PartialView("~/Views/Shared/Partials/_GitUsersPartial.cshtml", users);
    }

    [HttpGet]
    public async Task<IActionResult> GetUpsertForm(Guid userId)
    {
        var user = new GitUser();

        if (userId != Guid.Empty)
        {
            user = await _gitUserRepository.GetByKeyAsync(userId);
        }

        return PartialView("Upsert", user);
    }

    [HttpGet]
    public async Task<IActionResult> CheckUsername(string? username)
    {
        var result = await _gitService.CheckUsername(username);

        if (result.Success)
            return Ok();

        return BadRequest(result.Message);
    }

    [HttpPost]
    public async Task<IActionResult> CreateUser(string? username)
    {
        if (string.IsNullOrEmpty(username))
            return BadRequest("Username must be specified");

        var userQuery = await _gitUserRepository.GetAsync(x => x.Name == username);

        if (userQuery is not null && userQuery.Any())
            return BadRequest($"Username '{username}' already exists in JSON");

        var githubUser = await _gitService.CheckUsername(username);

        if (githubUser.Success)
        {
            var user = githubUser.ResponseObject;
            var createResponse = await _gitUserRepository.CreateAsync(user);

            return Ok("User created successfully");
        }

        return BadRequest(githubUser.Message);
    }

    [HttpPost]
    public async Task<IActionResult> DeactivateUser(Guid userId)
    {
        var user = await _gitUserRepository.GetByKeyAsync(userId);

        if (user is not null)
        {
            user.IsActive = false;
            await _gitUserRepository.UpdateAsync(user);

            return Ok();
        }

        return BadRequest();
    }

    [HttpGet]
    public async Task<IActionResult> GetRepositoriesForUser(string? username)
    {
        var repos = await _gitService.GetRepositories(username);

        if (!repos.Success) 
            return BadRequest(repos.Message);

        var model = new GitRepositoriesViewModel()
        {
            Username = username,
            GitRepositories = repos.ResponseObject
        };

        return PartialView("~/Views/Shared/Partials/_GitUserRepositoriesPartial.cshtml", model);
    }
}

Gitar.Web/Controllers/HomeController.cs
using Gitar.Domain.Contracts.Data;
using Gitar.Domain.Models;
using Gitar.Web.Models;
using Infrastructure.Data.Json.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gitar.Web.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            //var obj1 = new GitUser()
            //{
            //    Name = "prvi"
            //};

            //var obj2 = new GitUser()
            //{
            //    Name = "drugi"
            //};

            //var obj3 = new GitUser()
            //{
            //    Name = "treci"
            //};

            //var obj4 = new GitUser()
            //{
            //    Name = "cetvrti"
            //};

            //var obj5 = new GitUser()
            //{
            //    Name = "peti"
            //};

            //var result1 = await _gitUserRepository.CreateAsync(obj1);
            //var result2 = await _gitUserRepository.CreateAsync(obj2);
            //var result3 = await _gitUserRepository.CreateAsync(obj3);
            //var result4 = await _gitUserRepository.CreateAsync(obj4);
            //var result5 = await _gitUserRepository.CreateAsync(obj5);

            //await _gitUserRepository.DeleteAsync(obj2.Id);

            //var user = await _gitUserRepository.GetAsync(x => x.IsActive == false);

            //var oneUser = await _gitUserRepository.GetByKeyAsync(obj1.Id);

            //oneUser.ModifyDate = DateTime.Now;
            //oneUser.Name = "novi prvi";

            //await _gitUserRepository.UpdateAsync(oneUser);

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gitar.Web/Views/Gitar/Index.cshtml
@model List<Gitar.Domain.Models.GitUser>

<div id="content-wrapper">
    <partial name="~/Views/Shared/Partials/_GitUsersPartial.cshtml" model="Model"></partial>
</div>

Gitar.Web/Views/Gitar/Upsert.cshtml
@model Gitar.Domain.Models.GitUser

<form method="post">
    <div class="row">
        <div class="col d-flex flex-row align-items-center justify-content-between">
            <input type="text" class="form-control w-75" placeholder="Github username" asp-for="Name" value="@Model.Name" id="github-username" />
            <button type="button" class="btn btn-sm btn-outline-primary" id="username-validate" onclick="CheckUsername()"> 
                <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true" id="username-validate-loader"></span>
                <i class="fa" id="validate-icon"></i> &nbsp; Validate
            </button>
        </div>       
    </div>
    <hr />
    <button type="button" class="btn btn-success w-100" onclick="SubmitUserForm()"> <i class="fa-solid fa-user-plus"></i> &nbsp; Add user </button>
</form>

<script>
    $(function() {
        toastr.options = {
            positionClass: "toast-top-left",
        };
    });

    function CheckUsername() {
        var $usernameInput = $('#github-username').val();
        var $validateIcon = $('#validate-icon');
        var $usernameLoader = $("#username-validate-loader");

        $usernameLoader.removeClass('d-none');
        $validateIcon.removeClass();

        if ($usernameInput) {
            $.get('/Gitar/CheckUsername', { username: $usernameInput }, function(response) {
                $validateIcon.addClass('fa-solid fa-check-double');
                $usernameLoader.addClass('d-none');
                toastr.info('Username is valid')
            })
            .fail(function(err) {
                $validateIcon.addClass('fa-solid fa-triangle-exclamation');
                $usernameLoader.addClass('d-none');
                toastr.error(err.responseText ?? "Unexpected error occurred", "Error");
            });
        }
        else {
            $usernameLoader.addClass('d-none');
            toastr.warning("Please provide a username", "Warning");
        }
    }

    function SubmitUserForm() {
        var $usernameInput = $('#github-username').val();
        var $usernameLoader = $("#username-validate-loader");

        if ($usernameInput) {
            $.post('/Gitar/CreateUser', { username: $usernameInput }, function(response) {
                toastr.success('User created successfully');

                $.get('Gitar/GetUsersPartial', function (responseHtml) {
                    $('#content-wrapper').html(responseHtml);

                    var $modalHolder = $('#modal-holder');
                    $modalHolder.modal('hide');
                });
            })
            .fail(function(err) {
                toastr.error(err.responseText ?? "Unexpected error occurred", "Error");
            });
        }
    }

</script>

Gitar.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Gitar - Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Gitar!</h1>
    <p> You can start by clicking Github Repository Viewer above </p>
</div>

Gitar.Web/Views/Shared/Partials/_GitUserRepositoriesPartial.cshtml
@model Gitar.Web.ViewModels.GitRepositoriesViewModel

<div id="repositories-wrapper">
    <div class="list-group">
        @foreach(var repository in Model.GitRepositories)
        {
            <a href="@repository.Url" target="_blank" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 align-items-center">
                    @if (repository.Fork)
                    {
                        <i class="fa-solid fa-code-fork" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Repository is forked"></i>
                        @: &nbsp; &nbsp;
                    }
                    <h5 class="mb-1">@repository.Name</h5>             
                </div>                
                <div class="d-flex w-100 justify-content-between">
                    <p class="mb-1"> @repository.Description </p>
                    <p class="mb-1" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Create date"> <i class="fa-regular fa-calendar-plus"></i> &nbsp; @repository.CreateDate.ToString("dd.MM.yyyy") </p>
                </div>
                <div class="d-flex w-100 justify-content-between">
                    <small class="text-secondary">@repository.Language</small>
                    <p class="mb-1" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Last push date"> <i class="fa-solid fa-code-pull-request"></i> &nbsp; @repository.PushDate.ToString("dd.MM.yyyy") </p>
                </div>
            </a>
        }
    </div>
</div>

<script>
    $(function () {
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    });
</script>

Gitar.Web/Views/Shared/Partials/_GitUsersPartial.cshtml
@model List<Gitar.Domain.Models.GitUser>

<button class="btn btn-success w-100" id="new-github-user"> <i class="fa-solid fa-user-plus"></i> &nbsp; Add new GitHub user </button>
<br />
<br />

<div class="d-flex flex-row flex-wrap align-items-center justify-content-center gap-lg-5">
    @foreach (var user in Model)
    {
        <div class="card shadow-lg" style="width: 350px">
            @{
                var imageUrl = string.IsNullOrEmpty(user.ImageUrl) ? "/assets/gitcat.png" : user.ImageUrl;
            }
            <img class="card-img-top" src="@imageUrl" alt="Github user">
            <div class="card-body">
                <div class="d-flex gap-2">
                    <h5 class="card-title"> @user.Name </h5>
                    <a href="@user.ProfileUrl" target="_blank" title="Open GitHub" data-bs-toggle="tooltip" data-bs-placement="bottom"> <i class="fa-brands fa-github"></i> </a>

                    @if (!string.IsNullOrEmpty(user.Blog))
                    {
                        <a href="@user.Blog" target="_blank" title="Open website" data-bs-toggle="tooltip" data-bs-placement="bottom"> <i class="fa-solid fa-globe"></i> </a>
                    }
                </div>
                <div>
                    <i class="fa-solid fa-users text-primary"></i> @user.Followers followers &bull; @user.Following following
                </div>
            </div>
            <div class="card-footer">
                <i class="fa-solid fa-calendar text-secondary"></i> &nbsp; 
                <small class="text-muted"> Created @user.CreateDate.ToString("dd.MM.yyyy") at @user.CreateDate.ToString("HH:mm")</small>
                <hr />
                <div class="d-flex flex-row justify-content-start gap-1" style="margin-bottom: 10px">
                    <button class="btn btn-sm btn-outline-danger user-deactivate-btn" data-id="@user.Id">
                        <i class="fa-solid fa-ban"></i> &nbsp; Deactivate
                    </button>
                    @if (user.PublicRepoCount > 0)
                    {                        
                        var repositoryCountDisplay = user.PublicRepoCount > 99 ? "99+" : user.PublicRepoCount.ToString();
                        
                        <button class="btn btn-sm btn-success user-repositories-btn position-relative" style="margin-left: auto !important" data-username="@user.Name">
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Public repository count">
                                @repositoryCountDisplay
                            </span>
                            <i class="fa-solid fa-code"></i> &nbsp; Repositories
                        </button>                        
                    }
                </div>
            </div>
        </div>
    }
</div>


<script>

    $(function () {
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
    });

    $('.user-deactivate-btn').click(function () {
        var userId = $(this).attr('data-id');

        Swal.fire({
            title: 'Warning',
            text: 'This action will deactivate selected user. Are you sure?',
            showCancelButton: true,
            icon: 'warning',
            confirmButtonText: 'Yes, deactivate user!',
            cancelButtonText: 'No'
        }).then((result) => {
            if (result.isConfirmed) {
                $.post('Gitar/DeactivateUser', { userId: userId }, function (response) {
                    toastr.success('User deactivated');

                    $.get('Gitar/GetUsersPartial', function(responseHtml) {
                        $('#content-wrapper').html(responseHtml);
                    });
                })
                .fail(function (err) {
                    toastr.error(err.responseText ?? "Unexpected error occurred", "Error");
                });
            }
        });
    });

    $('.user-repositories-btn').click(function() {
        var username = $(this).attr('data-username');

        $.get('/Gitar/GetRepositoriesForUser', { username: username }, function(response) {
            var $modalHolder = $('#modal-holder');
            var $modalBody = $modalHolder.find('.modal-body');
            var $modalTitle = $modalHolder.find('#modal-title');

            $modalTitle.html("<i class=\"fa-solid fa-code\"></i> &nbsp; " + username);
            $modalBody.html(response);
            $modalHolder.modal('show');
        });
    });

    $('#new-github-user').click(function () {
        $.get('/Gitar/GetUpsertForm', function (content, responseText, response) {
            if (response.status === 200) {
                var $modalHolder = $('#modal-holder');
                var $modalBody = $modalHolder.find('.modal-body');
                var $modalTitle = $modalHolder.find('#modal-title');

                $modalTitle.html("Edit or create new github user");
                $modalBody.html(content);
                $modalHolder.modal('show');
            }
        })
    });
</script>

Gitar.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gitar.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.4.0-web/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gitar.Web.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <!-- Modal -->
    <div class="modal fade" id="modal-holder" tabindex="-1" role="dialog" aria-labelledby="modal-holder" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-center w-100" id="modal-title"></h5>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gitar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gitar" asp-action="Index"> <i class="fa-brands fa-github"></i> &nbsp; Github Repository Viewer </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year Ajdin Hukara - <a target="_blank" href="http://neurouz.ddns.net"> Visit portfolio website </a>
        </div>
    </footer>

</body>
</html>